### ISSUE TITLE
Add Notes

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#101]
# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179)
 
This page can be found in "Tenant CMS (Prototype) " 

## Add Note Page

This is the page where users add new notes. 

- [ ] 1. [Top Navigation](#top-navigation)
- [ ] 2. [Text Card](#text)
- [ ] 3. [Buttons](#button)
 
![image](https://user-images.githubusercontent.com/14948326/85824887-09354c80-b7ab-11ea-8faa-46cf7d176820.png)

## 1. Top Navigation

USE THIS CODE https://github.com/whynotearth/BrowTricks/blob/master/src/components/BaseHeader.vue

<img width="691" alt="Screenshot 2020-06-25 at 13 11 48" src="https://user-images.githubusercontent.com/66247789/85717441-6e266f00-b6e5-11ea-9fae-99121fde3b6f.png">

## Content
Title: Notes
Back: (Leads to Notes #73 )

## Asset
<img width="85" alt="Screenshot 2020-06-25 at 13 16 44" src="https://user-images.githubusercontent.com/66247789/85718137-218f6380-b6e6-11ea-84ff-4b2b0ef014b0.png">

## Text Style
Title: 
```
/* Mobile H2 */

font-family: Caviar Dreams;
font-size: 20px;
line-height: Auto;
letter-spacing: 0.15em;
```

## Colours

Top Navigation Bar Background: Primary (#067BC2)
Title: On Primary, High Emphasis (#FFFFFF, 84%)

## Shadow 
Top Navigation Bar:
```
/* 4 dp */

background: #C4C4C4;
box-shadow: 0px 1px 10px rgba(0, 0, 0, 0.2), 0px 4px 5px rgba(0, 0, 0, 0.12), 0px 2px 4px rgba(0, 0, 0, 0.14);
```

## 2. Text Card

USE THIS CODE: https://github.com/whynotearth/BrowTricks/blob/master/src/components/BaseInputTextArea.vue

![image](https://user-images.githubusercontent.com/14948326/85824942-29fda200-b7ab-11ea-8560-699b6cbd93fe.png)

## Content 
Text Area Label: Note

## Colour
Card: Surface( #FFFFFF)

## Shadows 
Card: 
```
/* 1 dp */

box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.2), 0px 2px 2px rgba(0, 0, 0, 0.12), 0px 0px 2px rgba(0, 0, 0, 0.14);
border-radius: 12px;
```

## 3. Buttons

<img width="542" alt="Screenshot 2020-06-25 at 13 57 05" src="https://user-images.githubusercontent.com/66247789/85724075-c2345200-b6eb-11ea-8a9d-0b57f2688192.png"

## Contents 
Button 1 Text: SAVE NOTE (Saves note, returns to notes page #73 )

## Text Style
Button 1 Text, Text Button: 
```
/* Color Label */

font-family: Roboto;
font-style: normal;
font-weight: 500;
font-size: 14px;
line-height: 24px;
```

## Colour
Button 1 Text: On Secondary - High (#FFFFFF, 84%) 
Button 1 background: Secondary(#33658A)

## Shadows 
Button 1 Background: 
```
/* 2 dp */

box-shadow: 0px 1px 5px rgba(0, 0, 0, 0.2), 0px 3px 4px rgba(0, 0, 0, 0.12), 0px 2px 4px rgba(0, 0, 0, 0.14);
border-radius: 50px;
```

**Comment by paulchrisluke** [comment]
@abdullahcalisir12 dates should be available for notes now: https://github.com/whynotearth/meredith-core/issues/268#event-3593515218
