### ISSUE TITLE
Customer View - Home Page 

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#11]
This issue is for the customer view home page. The component colors and text are referred to as their previously set names here: #1 & #2 

![image](https://user-images.githubusercontent.com/5694308/78975501-6d4a5c00-7b3e-11ea-875a-960c2d454595.png)
![image](https://user-images.githubusercontent.com/5694308/78975549-85ba7680-7b3e-11ea-8c7b-a2bb3e9b37a0.png)

## Home Page
The homepage consists of several parts: 
1. Background 
2. Navigation 
3. Page Title 
4. Promo Message (if from promo link) 
5. Button 

### 1. Background 
![image](https://user-images.githubusercontent.com/5694308/78975581-94089280-7b3e-11ea-927e-70498f71a481.png)

The fullscreen background image is pulled from the database and will be part of the page api

### 2. Navigation
![image](https://user-images.githubusercontent.com/5694308/78975607-9ff45480-7b3e-11ea-9e1d-3e8e12c8cd29.png)
The icon will lead to the opening of the navigation menu #10 
Color; tenant site - On Background 
Emphasis: High

### 3. Page Title
![image](https://user-images.githubusercontent.com/5694308/78975715-e184ff80-7b3e-11ea-9ba5-dc977ff0a807.png)

This is the name of the tenant salon, centered. It is 16 pixels away form both the illlustrations and the promo message (or the button depending on site version) 
Font: Title
Color: tenant Site - On Background 
Emphasis: High

### 4. Promo Message (Only on promo flow) 
![image](https://user-images.githubusercontent.com/5694308/78975731-ecd82b00-7b3e-11ea-953a-f3f56e579a5d.png)
The promo message should only display if the user is coming from the promo link. 
"Lucky you! Our promo has {x} spots left! Book now for {x}% off!" Missing information is set by the tenant . Text area width limited to 312 pixels. 16 pixels from components above and below.
Font: Body 1
Color: tenant Site - On Background 
Emphasis: Medium

### 5. Button 
![image](https://user-images.githubusercontent.com/5694308/78975740-f366a280-7b3e-11ea-944a-e46a89adc07b.png)
The homepage button give site visitors a direct link to the booking process chatbot (promo or regular, depending on link they arrived from). It's 80 pixels from the bottom of the screen, horizontally centered. This outline button has 3 parts: 
1. outline 
2. Icon
3. Call to action Text  

**1. Outline**
![image](https://user-images.githubusercontent.com/5694308/77303083-e6ffde80-6d24-11ea-8619-68f88e01b972.png)
The outline of the button is 296x40 pixels. 
Color: tenant Site - On Background 
Outline Corner Radius - 3 pixels

**2. Icon**
![image](https://user-images.githubusercontent.com/5694308/77303135-fc750880-6d24-11ea-8756-e0d5ac805fdd.png)
Color: tenant Site - On Background 
Emphasis: High

**3. Call to Action Text**
The call to action text directs visitors to the booking flow 
Font: Color Label
Color: tenant Site - On Background 
Emphasis: High

**Comment by sally** [comment]
@paulchrisluke do we want vertically centered content for home or not? Figma is different than what is in the description for this Issue

Figma:

![image](https://user-images.githubusercontent.com/20192983/80315404-4336a200-87ac-11ea-968a-687db6b691f1.png)

Issue:

![image](https://user-images.githubusercontent.com/20192983/80315408-46ca2900-87ac-11ea-9665-1b492283b1f0.png)

**Comment by paulchrisluke** [comment]
The one that's closer to the bottom is the correct one, a updated setting changed their positioning within figma, sorry about that
