### ISSUE TITLE
Staging review

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#170]
# Saved Client info keeps disappearing 
This profile had my name and phone saved but now all o that information is gone :( only email is left 
![image](https://user-images.githubusercontent.com/14948326/89619646-811d8900-d8b8-11ea-873c-054912bd999c.png)

# PMU Status Not Updated 
Status is not updated even if button is available to download signed PMU 
![image](https://user-images.githubusercontent.com/14948326/89616279-4d3f6500-d8b2-11ea-9fc8-730b022a895b.png)

# PMU Download Button Placement 
Maybe move this button from this page https://staging.browtricksbeauty.com/tenant/test-tenant-94/clients/edit/45 to https://staging.browtricksbeauty.com/tenant/test-tenant-94/client/45/pmu-sign ?
![image](https://user-images.githubusercontent.com/14948326/89615511-f8e7b580-d8b0-11ea-9581-e4bf863ee93f.png)

# Custom question visible, no option to sign
The custom questions added are shown on the PDF on hellpsign, but there are no options for signatures on the hellosign file 
![image](https://user-images.githubusercontent.com/14948326/89616361-7829b900-d8b2-11ea-8b3b-b1fbe5d1452b.png)

# Navigation Drawer does not close on mobile home page 
It doesn't close when clicked right now when you press "home" to return to home page, so on mobile it just stays on navigational drawer and doesn't move. 
When pressing "Home" on https://staging.browtricksbeauty.com/ 's navigational drawer, it should close to show home page
![gif](https://i.gyazo.com/fc30ac1230e12eb5db7dba469f9be149.gif)

**Comment by mort3za** [comment]
> The custom questions added are shown on the PDF on hellpsign, but there are no options for signatures on the hellosign file

@ctyar can you add it?

**Comment by mort3za** [comment]
@ctyar is working on this:  
Custom question visible, no option to sign

This issue "PMU Status Not Updated" should not appear for new clients. If it occured again, report please.

**Comment by ctyar** [comment]
The ` Custom question visible, no option to sign` should be fixed now
