### ISSUE TITLE
if pressing back, page transition should slide left

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#173]
# Back Button Transitions 
When pressing back, the page transition should slide left in a way where it seems like the new page is pushing the previous page from the left to the right. 

A similar transition has previously been used in Volkswagen tab contents, where the contents of one tab are pushed one side or another depending on selected tab: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/09fe9a5b49c7454c2f55a467d88fc358415fbb79/src/components/BaseTabsAnimation.vue

### Please see tik tok back button navigation below: 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14948326/89759187-ca1d4980-db13-11ea-84a0-3adb0f0db25f.gif)

# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179)

See page "Tenant CMS (Prototype)

**Comment by giteshk11** [comment]
we can close this i think @paulchrisluke
