### ISSUE TITLE
show spinner while loading page, with top and bottom nav fixed and not transition

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#174]
# Add Spinner while Loading Pages 
While navigating and loading between pages. a spinner should show so users can see that the page is currently loading and not just empty. The top and bottom nav should remain **fixed** and not transition. 
The spinner for Browtricks has been previously created here: https://github.com/whynotearth/foodouken.com/pull/91

We also want to add a crown in the middle of the loading circle that spins with the spinner circle. Asset is located here: 
[Browtricks Placeholder (2).zip](https://github.com/whynotearth/BrowTricks/files/5084893/Browtricks.Placeholder.2.zip)

### Please see tik tok between bottom nav pages below: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14948326/89756098-b7067b80-db0b-11ea-987f-bedc7b1efe18.gif)

# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179)

See page "Tenant CMS (Prototype)

**Comment by mort3za** [comment]
@bamboochow Is this the spinner you want? (the PR you mentioned is using this heart)  
![image](https://user-images.githubusercontent.com/510242/90407939-5bfcf780-e0bc-11ea-8943-d167f2c0f66b.png)

**Comment by bamboochow** [comment]
@mort3za 
https://github.com/whynotearth/BrowTricks/pull/61
this was the PR i was looking for, sorry linked the wrong one 

Just have to change the spinning circle to this logo: 
[Browtricks Placeholder (2).zip](https://github.com/whynotearth/BrowTricks/files/5084892/Browtricks.Placeholder.2.zip)
