### ISSUE TITLE
Add Image/Video Sharing

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#181]
# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179)

**You can find the designs for this issue in the "Tenant CMS" Page of Figma**

# Asset 
[share.zip](https://github.com/whynotearth/BrowTricks/files/5060741/share.zip)

# Replace Download with Native Share option to Video/Image view 
We are replacing our download feature with the sharing option to our current image gallery view. When they select the share button, users must be able to have the option of (at least): 
- copying image/video link
- download
- share to their social media based on their native sharing feature 

![image](https://user-images.githubusercontent.com/14948326/89977530-86eae400-dc95-11ea-8969-17a1a3103e94.png)

Ideally we would want it to show something like tiktok, shown below (i was told this is all one line of code?) or the device's native sharing feature, like iphone's (also shown below)
![image0 (19)](https://user-images.githubusercontent.com/14948326/89977871-6e2efe00-dc96-11ea-9ba7-3313c33aede8.png)
![image0 (20)](https://user-images.githubusercontent.com/14948326/89977908-7dae4700-dc96-11ea-87ca-356283f014c2.png)

**Comment by paulchrisluke** [comment]
this should share to insta too https://github.com/whynotearth/BrowTricks/issues/190 @mort3za
