### ISSUE TITLE
Changing PMU Flow process to be PDF preview focused

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#185]
# Design File 
https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179
This is the design file for Brow Tricks. The "Tenant CMS" page contains all the screens necessary for the app 

The prototype for this flow is here: https://www.figma.com/proto/qsnqMoGP7zLhGjoRuRHTKk/Untitled?node-id=2%3A6&viewport=-946%2C513%2C0.8717118501663208&scaling=min-zoom

# PMU Form Setup  
We are changing the PMU flow so that for each individual client, the tenant have to upload a PDF individually. They are also able to add custom questions for each client. 

1. Tenants access this page through the PMU expansion in a client's profile. 
2. The first screen shows the uploader empty state. As a pdf/images are uploaded, they are shown in a preview. 
3. The users are also able to add optional custom questions/agreements to their generated form previews. These generated previews will be added as a new page at the end of the PDF preview. 
4. Tenants will then save this PMU form setup, which shows a success screen, and the page changes to allow customers to complete the form 

![image](https://user-images.githubusercontent.com/14948326/90090075-4ea6dc80-dd4d-11ea-8f76-5f11822aca84.png)

# Updated PMU Flow 
1. The client pmu page is changed to show the preview and "text to {number}" and "complete now" button. 
2. "Text to client" button will send pmu request text to client, and show tenant a success screen that request has been sent 
3. "Complete now" button leads to welcome page for PMU
4. The PMU form has been shortened to a one-step process that shows all preset PDF pages. Clients must scroll through the entirety of the pages in order to press "I agree" button. This page is the same as the "review and sign" step in our original flow 
5. Success screen shows, and generated signed PMU PDF preview is saved to the client's profile. 
6. The client PMU page will now show the signed PDF preview as well as a button that downloads PDF to device. 

![image](https://user-images.githubusercontent.com/14948326/90091520-d17d6680-dd50-11ea-8128-4bdf1dd97181.png)
![image](https://user-images.githubusercontent.com/14948326/90091982-f0c8c380-dd51-11ea-9187-9252a08ba313.png)

# PMU Form Status Update 
We are adding various status updates based on progress in filling out the form 
Incomplete: Form has not been generated or sent to client 
![image](https://user-images.githubusercontent.com/14948326/90026015-fd610380-dce0-11ea-9aaf-37b721cc7ba0.png)

Pending: Form link has been sent to client, but client has not completed
At this stage, tenants are able to resend their form request text, or the client can complete it in person 
![image](https://user-images.githubusercontent.com/14948326/90025908-defb0800-dce0-11ea-8117-7df3c2989698.png)

Completed: Client has completed the form, and client PMU page shows completed form as well as option to download the PDF 
Also includes Date and time at the bottom to indicate 
![image](https://user-images.githubusercontent.com/14948326/90026499-92fc9300-dce1-11ea-887b-773ae6db474d.png)

**Comment by ctyar** [comment]
I don't think we can accept raw PDF files from tenants.
Before we use a PDF template we need to do some preprocessing on it to add the custom fields (name, conditions, initials, date, signature, ...)
For example, to add the name field to the PDF right now we add an invisible special text to the PDF `[text|req|sender|Name|Name]` which for HelloSign means accept a name field here which I will send it's value to you before the user starts the signing.
I don't think it's possible to accept the raw PDF from the tenants

**Comment by paulchrisluke** [comment]
@ctyar the pdf/image upload is meant to add another page to our pdf template

"{{tenant}} has attached the following documents for your review, by agreeing to this document, you also accept the terms outlined in these documents"

and then its just an image of the uploaded pdf underneath?

The idea is to let them use their already existing disclosure forms, as well as add custom questions if needed. We don't need to add any fields or "read" that pdf in any way other than making it an image and attaching it to the total document.

is that possible?

**Comment by paulchrisluke** [comment]
@ctyar and I spoke on https://twitch.tv/paulchrisluke we should probably just allow a huge text field that supports markdown, and allow users to copy and paste their existing forms in there.

**Comment by mort3za** [comment]
I just updated the PMU sign page to have a markdown editor for every disclosure. Test on staging.browtricksbeauty.com

**Comment by paulchrisluke** [comment]
markdown looks good @mort3za

**Comment by paulchrisluke** [comment]
this is still pending backend to be reviewed correct? @mort3za @ctyar ?

**Comment by mort3za** [comment]
Yeah CT is testing

**Comment by ctyar** [comment]
Everything seems fine

**Comment by paulchrisluke** [comment]
@ctyar @mort3za we should remove hellosign from this process, and generate our own previews

**Comment by paulchrisluke** [comment]
@ctyar @mort3za , we can have a huddle on discord about this when you guys come online, just message me. https://pmusign.com/

this is the current standard, but not something we need to do with all these functions.

tenants should be able to log in

1. create a form (home > PMU form > add a lot of custom questions
2. request form completion from client (client > pmu form > request)
- we generate a pdf version of these questions and twilio sms to the user
3. client should hit a landing page asking if they accept  (this can be VERY simple, no signature or anything needed, just a checkbox)
- this page displays the generated pdf with a checkbox to accept
4. if they do, we save the pdf to their profile under the client pmu sign tab with date/time agreed to
