### ISSUE TITLE
upload sharing should include to instagram

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#190]
staging.browtricksbeauty.com

Our current sharing features on our customer upload page https://staging.browtricksbeauty.com/tenant/test-tenant-94/clients/74/uploads uses the native device sharing feature, and includes many common apps we use (facebook, snapchat, linkedin, tiktok, etc) but does not include instagram. 

Our sharing feature should include instagram story, post creation, and direct messages. 

For example, our current fb sharing features allows for our images to be directly used for posts 
Reddit app also allows for instagram image sharing directly from its app.

**Comment by mort3za** [comment]
![Screenshot_20200820-174244_Android System](https://user-images.githubusercontent.com/510242/90775757-75957d80-e30e-11ea-865d-cdf9c905df53.jpg)

I see Instagram in the share menu, this is exactly same sharing menu when I want to share a video from Android's gallery (Instagram direct isn't available for sharing a video from gallery too)

**Comment by mort3za** [comment]
This was Android though. In iPhone because we're sharing a URL instead of the actual video file, it's different.  
If you've seen any website (not a native app) that can share a video directly from web, I can check it but I don't think it's possible for iPhone (in iOS 13).

**Comment by paulchrisluke** [comment]
is it possible to redirect to the camera roll or isntagram itself? 

Could we add a button that redirects to open these apps?

**Comment by mort3za** [comment]
Why would we like to open the camera roll from our gallery? 🤔 

The only thing I found is that we can add a link to an Instagram user page. Clicking that link, will open the app and will show the user page.  
Like this `<a href="instagram://user?username=nasa">Nasa</a>`

**Comment by mort3za** [comment]
For opening camera to upload images, in Cloudinary widget by selecting "My files", Android gives an option to open camera and take pictures, if you meant that.
