### ISSUE TITLE
Set Up Color Styles

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#2]
![image](https://user-images.githubusercontent.com/5694308/76734762-2dd65d00-6796-11ea-971f-0e582c581729.png)
We are setting up all styles for Brow Tricks, our salon booking app 

Here are the color styles for Brow Tricks: 
Primary Color (#7ACCEA)
Secondary Color (#ABEDFC)
Background Color (#F4F1F1)
Surface (#FFFFFF)
Icon/Action Color (#0C6986)
On Primary (High/medium/Disabled) (#0C6986)
On Secondary (High/Medium/Disabled) (#0C6986)
On Background (High/Medium/Disabled) (#000000)
On Surface (High/Medium/Disabled) (#000000)
Error (#C04545)
White On Primary (#FFFFFF)
Radial Button Background
![image](https://user-images.githubusercontent.com/5694308/76736242-0c2aa500-6799-11ea-8a17-ede05c34d352.png)

Similar to Saya, our content colors are separated into 4 opacities: high, medium, disabled, divider
- High (100%)
- Medium (54%)
- Disabled (38%)
- Divider (12%)

![image](https://user-images.githubusercontent.com/5694308/76747546-e5299e80-67ab-11ea-8ddf-ab63e5d6c87e.png)

### Design File
The specs for each individual color style can be found in the [Figma design file](https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=715%3A7751)
To see all local styles, click on the canvas background (anywhere that doesn't have a component), and the list of local styles will show up on the 
To see specifics for a local style, click on the "adjustment" icon that appears on hover over a local style. 
![image](https://i.gyazo.com/00ec510ba2fd5f983f43e3efc9680ab9.gif)

**Comment by sally** [comment]
@paulchrisluke Could you double check the hex code we want for "on background"? Right now on the Issue it says it should be different opacities of `#000000` but we make reference to "on background" in [#11 (Customer View - Home Page)](https://github.com/whynotearth/BrowTricks/issues/11) which leads me to believe we wanted "on background" to be white `#FFFFFF`

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/80332685-b6f0b180-8875-11ea-80c2-b30bd3a9946c.png)
For the customer view, because of its different background style, we've set a separate set of "on background" at different opacities that is specifically for the sites 

On our Tenant CMS, we are using black for our "on background". 

So, for customer site - on background is #FFFFFF
tenant CMS - on background is #000000

Apologies that it's confusing, I'm still waiting on Morteza to give me the correct color naming conventions according to your updated color setup that you previously discussed with him, but feel free to suggest one
