### ISSUE TITLE
handle back button in notes

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#215]
using the back gesture on android and other devices should go back in notes

This doesn't need event handlers, just needs to add a separate route for note items and when user touches back button we should go to previous route.

**Comment by bamboochow** [comment]
![image0 (17)](https://user-images.githubusercontent.com/14948326/96871463-88f2cf80-149c-11eb-8544-4de7797dfc3c.png)

Bottom nav should stay still as we are moving between pages @abdullahcalisir12 
otherwise works great
