### ISSUE TITLE
Create Uploader and Tenant Bottom Navigation refactor 

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#220]
![image](https://user-images.githubusercontent.com/14948326/91040641-c96ad400-e638-11ea-8921-dfc569478f2b.png)

# Upload Steps 
To upload: 
1. tap + button in bottom nav
2. Select image or video for upload 
3. Upload image via Cloudinary 
4. REQUIRED: Select client in uploader page, add description, post image with button
5. Uploaded image appears in selected client's profile 

# Bottom Navigation 
Our bottom navigation will be present on all pages to allow for easy access to upload feature. It would have the following buttons: 
- Home (opens #214 Home Page)
- Client (opens #55 Client list) 
- PMU Forms (opens #119 PMU Form Setup)
- "+" button: Opens uploader drawer to select between uploading image or video (feature locked #218 ) 

# Uploader Page 
The uploader page contains: 
- A text area for description input (error validation for client shown in screenshot above)
- a "service" button which opens up a list of services and adds it to description with a hashtag
- REQUIRED ACTION: a "client" button that adds an @{client name} to the description and saves image for that client
- Share button that opens device native sharing feature 
- Button that saves uploaded inmage & information

**Comment by paulchrisluke** [comment]
@bamboochow need design update for when service is chosen
