### ISSUE TITLE
more streamlined sign up process

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#234]
Prototype: https://www.figma.com/proto/JSQ8RhDK6nQa0NlaaWvVd7/BrowTricks-Log-in-Sign-up?node-id=2%3A99&viewport=798%2C474%2C0.7567259669303894&scaling=min-zoom

users should sign up/log in like tik tok. 

The sign up drawer is where the users are able to sign up for an account. They can find set up CTA buttons at: 
- my account page when not logged in 
- Settings page --> manage account (not logged in) 
- Add account in Settings 
- Add account in account toggle (my account page) 

Signup process is prompted by the signup drawer: 
1. social logins will start the sign up process (if gmail account already connected, log in instead) 
2. Verify age with birthday 
3. Verify email or phone number (with country code selection, not just set to KH something like this https://louismazel.github.io/vue-phone-number-input/ I think we've also done this in vkririom). They are able to verify the other method independently after their account is fully set up. 

USE https://www.twilio.com/blog/html-attributes-two-factor-authentication-autocomplete

4. username selection
5. Shove them into the app into "my account". They can setup their business as they like, but cannot activate site/allow booking/upload image until subscription starts 
we can do business upgrade info later in the ux process if they want to upgrade

Log in can be accessed through the settings page or through the sign up drawer "already have an account?" prompt: 
1. social login via fb or gmail 
2. Goes directly to user's my account page 

![image](https://user-images.githubusercontent.com/14948326/91656288-d298ec80-eae1-11ea-942a-61c797b4f8e5.png)

![image](https://user-images.githubusercontent.com/14948326/91629341-69867b80-e9f2-11ea-9b49-895c20b3989e.png)

**Comment by mort3za** [comment]
I suggest using cog icon instead of 'more' for linking to settings page.

**Comment by paulchrisluke** [comment]
agree @mort3za , @bamboochow can youu please provide svg?

**Comment by bamboochow** [comment]
[Setting.zip](https://github.com/whynotearth/BrowTricks/files/5172524/Setting.zip)
Settings Cog SVG according to @mort3za and @giteshk11 's suggestions ;P 

![image](https://user-images.githubusercontent.com/14948326/92196927-8d3a3d80-ee9a-11ea-9004-29073f99cf68.png)

**Comment by giteshk11** [comment]
Looks good @bamboochow
