### ISSUE TITLE
Client "more" menu wrong position

### ISSUE THREAD

**Issue by mort3za** [whynotearth/BrowTricks#246]
This happened to me:  
![image](https://user-images.githubusercontent.com/510242/91652010-6057e600-eaa8-11ea-939d-854015b7a811.png)

In client page, 1920px screen.

**Comment by giteshk11** [comment]
can you explain more about this issue @mort3za ?

**Comment by mort3za** [comment]
The overflow menu of client page for one time became like the screenshot (moved to top, outside of browser viewport).  
Couldn't reproduce it but maybe you can guess what causes it in the code. I guess it can happen on certain page loading states.

**Comment by giteshk11** [comment]
![image](https://user-images.githubusercontent.com/17675390/91653228-47f1c680-eabc-11ea-995b-61c74b78e26e.png)
i tested on 1920x1080 via browserstack

**Comment by paulchrisluke** [comment]
I think this can be replicated by going to edit client profile and using the back gesture
