### ISSUE TITLE
add meta data so when we share https://browtricksbeauty.com/

### ISSUE THREAD

**Issue by mort3za** [whynotearth/BrowTricks#266]
it shows logo, description, etc

**Comment by paulchrisluke** [comment]
Brow Tricks Beauty simplifies your client management. Add photos, videos, create custom PMU forms, add notes, and more! Brow Tricks Beauty gives you a way to keep relationships personal… and clients coming back.
Brow Tricks Beauty | PMU, Simplified.
some image version of our pretty lady... we don't have a landscape version right now...
