### ISSUE TITLE
add bottom nav to all screens

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#279]
if not logged in, prompt sign up drawer.

my account settings should allow logout

Component is built here: https://github.com/whynotearth/blobby/blob/master/src/components/BottomNavigation.vue

need to change icons to browtricks icons

![image](https://user-images.githubusercontent.com/5694308/93556034-e1b4e100-f9a1-11ea-9f83-3538d07aa0d0.png)

**Comment by mort3za** [comment]
Description is not clear for me.  
We have logout in my account.  
Which icons?  
What means all screens? even homepage (not logged in)? If I add navigation to homepage, what should I show in navigation in homepage?

**Comment by paulchrisluke** [comment]
@mort3za I apologize.

This should be the new browtricksbeauty.com home page
![image](https://user-images.githubusercontent.com/5694308/93766463-a257f000-fc40-11ea-85a5-f7f270ef5634.png)


logging in puts you in the app home page
sign up sends you to the sign up flow

Bottom nav should be used on screens after sign up (example after setting up your first forms, you should see bottom nav everywhere, including when you are making/editing new forms)
