### ISSUE TITLE
Icon Asset File

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#28]
![image](https://user-images.githubusercontent.com/5694308/80183960-f9c34700-8633-11ea-87da-441318fb6a56.png)

[BrowTricks Icons.zip](https://github.com/whynotearth/BrowTricks/files/4527202/BrowTricks.Icons.zip)
Attached are all icon current assets related to BrowTricks, in SVG format 

They are named according to Material Design 
https://material.io/resources/icons/?style=baseline

**Comment by sally** [comment]
@paulchrisluke Can we get a `keyboard_arrow_left` as well? Seen here

![image](https://user-images.githubusercontent.com/20192983/80240881-7562cb00-8617-11ea-9bc2-75c83de0cc9c.png)

**Comment by sally** [comment]
Also not sure if this is supposed to be an svg or not, but if it is, then the hamburger menu icon too?

![image](https://user-images.githubusercontent.com/20192983/80241081-d9858f00-8617-11ea-8ab6-86c75101175d.png)

**Comment by paulchrisluke** [comment]
Here are the rest of the icons you mentioned @sally 
[Icon.zip](https://github.com/whynotearth/BrowTricks/files/4532306/Icon.zip)
