### ISSUE TITLE
Remove Trailing Spaces in form inputs

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#298]
Component: https://github.com/whynotearth/BrowTricks/blob/staging/src/components/inputs/MaterialInput.vue

Similar issue here which is almost completed: https://github.com/whynotearth/foodouken.com/pull/318

```
  },
  filters: {
    trim: function(value) {
      return value.trim();
    }
```

```
      :value="value"
      :value="value | trim"
```

Try using v-model.trim="yourModel" on MaterialInput elements. That should fix the issue.

**Comment by colinkiama** [comment]
Do you mind if I take this one?

**Comment by mort3za** [comment]
Go ahead!

**Comment by colinkiama** [comment]
So is "form inputs" referring to all the inputs on the website (**MaterialInput** component) or the inputs from the PMU forms that clients complete?

**Comment by paulchrisluke** [comment]
Material input! Primarily when someone is signing up for a new account and
they add a space at the end of their email it doesn't work.
