### ISSUE TITLE
upload pdf button doesn't work in pmu form builder

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#304]

**Comment by mort3za** [comment]
I just created a template with a pdf upload question. this was my pdf file:
[google.pdf](https://github.com/whynotearth/BrowTricks/files/5246888/google.pdf)

And the preview looks fine too:  
<img src="https://user-images.githubusercontent.com/510242/93623502-16ea1f00-f9f4-11ea-934e-1ab141e7dd31.png" width="500" />

If you can, please write the steps to reproduce the bug.
