### ISSUE TITLE
simplify sign up

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#341]
we still have the old sign up process in place, it should be like this

![image](https://user-images.githubusercontent.com/5694308/94457544-e7e76080-01de-11eb-966d-3280f4087a5c.png)

we no longer ask for business hours, logo, notification style, or payment methods accepted.

we added usernames, phone verification, and email password reset. Tagging @ctyar for awareness. This can happen tomorrow @mort3za

**Comment by mort3za** [comment]
> we added usernames, phone verification, and email password reset

- [x] phone verification
- [ ] username 
- [ ] email password reset

@paulchrisluke Where should I add username, in signup form? What happens to current users?  

> we no longer ask for business hours, logo, notification style, or payment methods accepted.

Is there any Figma design for tenant creation form?

**Comment by mort3za** [comment]
We should add SMS sending limitation later, like a timer or something.

**Comment by paulchrisluke** [comment]
@mort3za it looks like this https://romantic-swanson-ead31b.netlify.app/signup except phone number instead of email. We can force the current browtricks users to remake if needed, she has not released it to users yet

**Comment by mort3za** [comment]
@ctyar 

`BusinessHours: ["The BusinessHours field is required."]
NotificationTypes: ["The NotificationTypes field is required."]
PaymentMethodTypes: ["The PaymentMethodTypes field is required."]` 

These fields shouldn't be required.

**Comment by ctyar** [comment]
@mort3za done
