### ISSUE TITLE
SMS code starting with zero has problem

### ISSUE THREAD

**Issue by mort3za** [whynotearth/BrowTricks#352]
Seems API has issue with verification codes starting with zero, like 083703

POST Request URL: https://stagingapi.whynot.earth/api/v0/authentication/confirmphone

`{"errors":{"":["Input string '083703' is not a valid number. Path '', line 1, position 6."],"token":["The token field is required."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"|baac4c3c-44d708b630419500."}`

**Comment by ctyar** [comment]
I can't reproduce this
