### ISSUE TITLE
after account creation, route to home page + ux changes

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#369]
instead of forcing to the pmu form creation first, can we allow users to go to the home screen after account creation?

Then, when they click clients, they see empty state and can start adding clients or when they click pmu form builder they see our empty state "start making your pmu forms".

There are instances where some of her users will only use the client management portion, and she wants to give users the opportunity to navigate the app as quickly as possible.

**Comment by mort3za** [comment]
@ctyar for awareness

**Comment by mort3za** [comment]
I'll show the "Create PMU Form" page just after selecting PMU in client page, **if** tenant has no form template.  
So after user sign up we just have tenant creation form.

**Comment by paulchrisluke** [comment]
perfect !
