### ISSUE TITLE
"preview pdf" button on form builder

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#370]
https://staging.browtricksbeauty.com/tenant/paul-146/form-templates/item/71/edit

as you create pmu forms, re-arrange, add questions, we should show a preview of the final generated preview below

since live generation will be server costly, we can add a button at the bottom which says "preview pdf" and  then shows them the final pdf view... this could display in our image preview view

The PDF preview should scroll vertically as pages (like tiktok), with
- the name of the template file displayed as well as the date/time created
- a button that sends the tenant a test text to preview customer view 
- share and download pdf features like image preview 

The "Preview and test" button should only show if questions are added to the form template

![image](https://user-images.githubusercontent.com/14948326/95191207-9b151280-07fa-11eb-89fe-9b5433c2c86c.png)

**Comment by paulchrisluke** [comment]
@bamboochow can you get a design for this please?

**Comment by paulchrisluke** [comment]
@ctyar @mort3za what is the difficulty difference between having a show preview button which opens up the pdf in our image viewer or

"Send test" which sends a test version to the tenants number ?

**Comment by mort3za** [comment]
@paulchrisluke No difficulty in **frontend** side. just needs a design.

**Comment by paulchrisluke** [comment]
@mort3za design above, Julia updated the description
