### ISSUE TITLE
Add description input and client tagging to Image Uploader and description to Image preview

### ISSUE THREAD

**Issue by mort3za** [whynotearth/BrowTricks#382]
@ctyar for awareness.

**Comment by paulchrisluke** [comment]
bug in staging, unable to post a photo 
![image](https://user-images.githubusercontent.com/5694308/95158427-c598a880-07c5-11eb-9e94-f04173916a2d.png)

**Comment by mort3za** [comment]
> bug in staging, unable to post a photo
> ![image](https://user-images.githubusercontent.com/5694308/95158427-c598a880-07c5-11eb-9e94-f04173916a2d.png)

CT has fixed it.

**Comment by bamboochow** [comment]
![image](https://user-images.githubusercontent.com/14948326/95192206-090e0980-07fc-11eb-89ea-886cb9695c0f.png)

@mort3za This is the design for this issue
