### ISSUE TITLE
accept phone number in username field

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#383]
how hard is email too?

![image](https://user-images.githubusercontent.com/5694308/95158220-41debc00-07c5-11eb-8aca-136e85b55574.png)

**Comment by paulchrisluke** [comment]
@ctyar I think email, phone number, and even facebook endpoints exist? @giteshk11 is working on this, do we have those endpoints? Can I send phone, email, username in the same request?

**Comment by mort3za** [comment]
Login accepts username or email. We can detect the type of input text and send the appropriate request.  


In Swagger:  
POST /api/v0/authentication/login
```
{
  "userName": "string",
  "email": "string",
  "password": "string"
}```

**Comment by paulchrisluke** [comment]
@giteshk11 talked with @ctyar all login endpoints should work for login:

phone number, email, username 

OR

facebook

**Comment by ctyar** [comment]
@paulchrisluke I think you misunderstood me
The possible combinations for login:
Email and password, username and password, Google, and Facebook
Currently, we don't support phone number and password
