### ISSUE TITLE
Create a Page with Account Information

### ISSUE THREAD

**Issue by SaarthakDeshmukh** [whynotearth/BrowTricks#388]
# Design

**As a** Tenants 
**I want to** have a page where I can edit all the information like (profile image, first name, last name, username, and bio)
**So that I can** keep the profile updated.

Acceptance Criteria
**Given** it is accessible from the settings page
**When** they can edit and press a button to save
**Then**  it should update the information in your account profile (name, username, bio)

![Capture](https://user-images.githubusercontent.com/63605352/95379696-02f45780-08e6-11eb-8c24-cc01a6630cac.JPG)

**Comment by paulchrisluke** [comment]
@SaarthakDeshmukh if available, should we show phone and email as well? We ask for this info on sign up

**Comment by SaarthakDeshmukh** [comment]
Hey, Sorry for the late reply, @paulchrisluke We can add Phone and email if you want. But then the design will change a lit bit. Do you want to check it with @bamboochow
