### ISSUE TITLE
Create Settings Page

### ISSUE THREAD

**Issue by SaarthakDeshmukh** [whynotearth/BrowTricks#389]
**As a** customer 
**I want to** have a Logout feature in my Settings page
**so that I can** easily logout 

Acceptance Criteria
**Given** I click on a button
**When** I want to logout
**Then** It should redirect me to the login page 

## Content and Text Style
Settings Page:
{ Title } : Mobile H2
{ Log In } : Mobile Body

![2](https://user-images.githubusercontent.com/63605352/95207993-cdb60f80-07e8-11eb-97e3-ea3bb5041b45.JPG)

**Comment by paulchrisluke** [comment]
@mort3za we can hide the buttons we don't currently support. This is mainly to add the help page and connect to zendesk:


Zendesk URL
Give this URL to your developers. It is used to connect to the app.
https://browtricksproductsorg.zendesk.com
App ID
Give this App ID to your developers. It is used to identify the app.
ae3339f468d9036dae9aba71f82ab6cbcfeb8082131c15cb
Client ID
Give this Client ID to your developers. It is used to identify the app.
mobile_sdk_client_8b1a6243dfb61bc77b4d




Android code snippet
Zendesk.INSTANCE.init(context, "https://browtricksproductsorg.zendesk.com",
    "ae3339f468d9036dae9aba71f82ab6cbcfeb8082131c15cb",
    "mobile_sdk_client_8b1a6243dfb61bc77b4d");
Support.INSTANCE.init(Zendesk.INSTANCE);

iOS code snippet
Objective-C
[ZDKZendesk initializeWithAppId: @"ae3339f468d9036dae9aba71f82ab6cbcfeb8082131c15cb"
    clientId: @"mobile_sdk_client_8b1a6243dfb61bc77b4d"
    zendeskUrl: @"https://browtricksproductsorg.zendesk.com"];
[ZDKSupport initializeWithZendesk: [ZDKZendesk instance]];

Swift
Zendesk.initialize(appId: "ae3339f468d9036dae9aba71f82ab6cbcfeb8082131c15cb",
    clientId: "mobile_sdk_client_8b1a6243dfb61bc77b4d",
    zendeskUrl: "https://browtricksproductsorg.zendesk.com")
Support.initialize(withZendesk: Zendesk.instance)

**Comment by mort3za** [comment]
Zendesk URL (https://browtricksproductsorg.zendesk.com/) opens this page:  

![image](https://user-images.githubusercontent.com/510242/98585006-d912c400-22db-11eb-93c2-a011b3399c22.png)

I don't think users know what is it, me neither. Also have no idea what should I do with these info: 

```
App ID
Give this App ID to your developers. It is used to identify the app.
ae3339f468d9036dae9aba71f82ab6cbcfeb8082131c15cb
Client ID
Give this Client ID to your developers. It is used to identify the app.
mobile_sdk_client_8b1a6243dfb61bc77b4d
```
