### ISSUE TITLE
Check enter key on login form

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#395]
pressing enter on forms does not submit

**Comment by mort3za** [comment]
Found the bug. When we hit enter, the model of input is not yet updated because it has not received a blur event.

**Comment by paulchrisluke** [comment]
@mort3za after this merge I am unable to create an account

https://github.com/whynotearth/BrowTricks/issues/401

**Comment by mort3za** [comment]
@paulchrisluke Fixed
