### ISSUE TITLE
Check share button in client page and form-template preview

### ISSUE THREAD

**Issue by mort3za** [whynotearth/BrowTricks#407]

**Comment by abdullahcalisir12** [comment]
@mort3za @paulchrisluke  Web Share Api works properly.
I tested on samsung j7 pro chrome
samsung s10 chrome
iphone11 Pro chrome and safari. But even for android and iso it has lack of supported devices.
Will be better to create a handle case like here https://codepen.io/ayoisaiah/pen/YbNazJ
