### ISSUE TITLE
do not require client or description in image uploader

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#417]

**Comment by paulchrisluke** [comment]
this may need an api change @ctyar , we can backlog this if its complex

**Comment by ctyar** [comment]
The API is now ready for these changes

**Comment by mort3za** [comment]
> do not require client or description in image uploader

Do not require **client** or it's a typo?! If so, where the uploaded media belongs to?

**Comment by paulchrisluke** [comment]
the tenant @mort3za is that difficult?

**Comment by mort3za** [comment]
@paulchrisluke It shouldn't be difficult.  

@ctyar I'm getting this error: 400 `The ClientId field is required`

**Comment by ctyar** [comment]
@mort3za yeah sorry, it should be fixed now
