### ISSUE TITLE
media should be sorted by latest in my account and client

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#424]
![image](https://user-images.githubusercontent.com/5694308/95607247-ab8ced80-0a85-11eb-86fc-dd7eb07cefd7.png)
https://gyazo.com/7171d86af73376112f423a69be24af73

**Comment by mort3za** [comment]
This can be done in backend

**Comment by paulchrisluke** [comment]
true, but I don't know if @ctyar has availability. These issues are coming from a review from fresh eyes

**Comment by mort3za** [comment]
@abdullahcalisir12  CT added date time to items in images/videos. because it's two different lists showing in one list, we need a sorting in frontend.

**Comment by abdullahcalisir12** [comment]
@mort3za did you solve this issue?

**Comment by abdullahcalisir12** [comment]
@mort3za you already solved this issue I think, I will assign it to you.
