### ISSUE TITLE
create intro pages

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#436]
Should occur after a successful sign up and business sign up.

We should be able to use https://github.com/whynotearth/blobby/tree/master/src/components/introduction

![image](https://user-images.githubusercontent.com/5694308/95655893-b783b880-0b34-11eb-8d05-9bda81e371f0.png)

Welcome to BrowTricks

Easily manage your clients and rock your relationships.  Organize and store all client communication, notes, photos, videos, and custom form creation!  

Clean up your phone storage
Organize your client photos onto client profiles.  Easily share stored photos, to social media or you client.  AND Videos too!

Create Custom PMU Forms
Use our pre-build form templates, or easily create your own.  Send forms via SMS to complete before their appointment.  

Timestamped Notes Keep you Organized
Track your client details, communication, reminders and more.

**Comment by mort3za** [comment]
@bamboochow when the text styles updated, please notify me

**Comment by bamboochow** [comment]
Text styles update in figma @mort3za
![image](https://user-images.githubusercontent.com/14948326/96997540-24974500-155c-11eb-91df-58c94a72f82c.png)
