### ISSUE TITLE
video preview doesn't work, stretches my account

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#445]
once uploaded, it does not show up under selected client.
preview appears broken 

big video stretches my account grid

![image](https://user-images.githubusercontent.com/5694308/96272907-e8faf900-0ff8-11eb-803d-21a401299b76.png)

![image](https://user-images.githubusercontent.com/5694308/96273080-23649600-0ff9-11eb-8105-494582d52dea.png)

**Comment by paulchrisluke** [comment]
@mort3za the stretching is fixed but I still see a blank square in the video uploader, I assume we should be thowing the thumbnail of the video?

**Comment by mort3za** [comment]
@paulchrisluke We use the video thumbnail right now, could you post your video  or it's cloudinary link here?

**Comment by paulchrisluke** [comment]
https://res.cloudinary.com/whynotearth/video/upload/v1603104613/BrowTricks/tenant_upload_dev/topnzcdo2zmssfam44nv.mp4
