### ISSUE TITLE
Customer View - Category Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#45]
# Design File 
https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179
This is the design file for Brow Tricks. The "Customer View" page contains all the screens necessary for this issue

# Category Page 
This page layout has already been created before in the Volkswagen project 
![image](https://user-images.githubusercontent.com/5694308/81148725-fcfcf200-8fa6-11ea-9f4e-d12b1549cdbb.png)

It has an identical top navigation and background to all the other pages for the Customer View 

# Category List Component 
![image](https://user-images.githubusercontent.com/5694308/81148948-70066880-8fa7-11ea-9a59-57e87d81fbd1.png)
Selecting one of these categories will open up the services gallery, which shows each individual service in an instagram story style gallery for that category

## Text Style
List item:
```
/* Mobile H3 */

font-family: Roboto;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 24px;
/* identical to box height, or 150% */
```

## Color 
List Item: On Background Image, High (#FFFFFF, 84%)

**Comment by sally** [comment]
@paulchrisluke Could I get an asset for that icon? Also, what do you think about making that icon the default for this kind of component (dubbed 'LineItem' component [here](https://github.com/whynotearth/BrowTricks/pull/44))? It might not really fit as a default for the contact list 'LineItem' component instantiations, but we could put in a special default for that one type.

**Comment by paulchrisluke** [comment]
![Placeholder Icon](https://user-images.githubusercontent.com/5694308/81374609-d74c2600-9129-11ea-8940-9f196dfac87d.png)
Yes, this can be the default
