### ISSUE TITLE
Username field needs a better validation (English characters, numbers, underscore)

### ISSUE THREAD

**Issue by mort3za** [whynotearth/BrowTricks#503]

**Comment by mort3za** [comment]
@ctyar do you use any regex for username field validation?

**Comment by ctyar** [comment]
Allowed username characters: `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+`
No, we don't use regex for this particular validation

**Comment by mort3za** [comment]
This is my regex in frontend for username: `/^[a-zA-Z0-9_]+$/`  
Allowing other characters is not reasonable I think. @ctyar
