### ISSUE TITLE
Staging - unable to view existing client profile

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#505]
I am unable to view an existing client profile i've created before, but i can see the client profile for a client i just created. When i try to look at my existing client profile, I am shown the error below. Also, in the error shown, I am moved back to the home page of the app, but it should redirect to client page 

![image](https://user-images.githubusercontent.com/14948326/97524428-3868fe00-19d7-11eb-9e42-621aa226aeaa.png)

![image](https://user-images.githubusercontent.com/14948326/97542025-a70a8380-19f8-11eb-8ffb-62ecb6c85e2f.png)
![image](https://user-images.githubusercontent.com/14948326/97542106-c2758e80-19f8-11eb-9111-f4536ecb1924.png)

**Comment by ctyar** [comment]
This should be fixed now
