### ISSUE TITLE
New Landing Page Design

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#524]
We are creating a new Landing Page design with this setup:
1. Video background Header with Copy (not set yet, use design sample text for now)
2. 3 video/feature text blocks that are horizontal in desktop, verticle in mobile 
3. Pricing Card page 
4. Final CTA Section 
5. Footer Linking to fb group, help page, and display phone number

Videos: 
https://we.tl/t-txyTZyH7Rm

Design: 
https://www.figma.com/file/FX2dv41L6bgviNM8b8y93H/chris-s-browtricks-draft?node-id=1261%3A11
in "04 - Login and Sign Up"

Prototype: 
https://www.figma.com/proto/FX2dv41L6bgviNM8b8y93H/chris's-browtricks-draft?node-id=1261%3A11&viewport=1625%2C520%2C0.16009651124477386&scaling=scale-down

![image](https://user-images.githubusercontent.com/14948326/98940062-fbdfeb00-251c-11eb-8fa9-3685b31872a8.png)

**Comment by mort3za** [comment]
> Prototype:
> https://www.figma.com/proto/FX2dv41L6bgviNM8b8y93H/chris-s-browtricks-draft?node-

Seems the prototype is empty  🤔 

Also, I need the background image of the section above footer (download app section circles pattern)

**Comment by bamboochow** [comment]
the site looks good, the home page cover video isn't there though, should be included in the above transfer link https://we.tl/t-txyTZyH7Rm

also, for these blocks, i want to match the colors to the videos a bit better, can you try these background colors?
EBBBB6 (pink)
CCE9DE (green)
F1E2D8 (champagne)
![image](https://user-images.githubusercontent.com/14948326/99624353-bcefef00-2a60-11eb-9720-ab0c9067671c.png)

This button is not linked to anything, should go to sign up https://deploy-preview-527--browtricks.netlify.app/signup
![image](https://user-images.githubusercontent.com/14948326/99624491-f7598c00-2a60-11eb-9fad-23801e284097.png)

CTA Section background image here: 
![Frame 352](https://user-images.githubusercontent.com/14948326/99625802-967f8300-2a63-11eb-9ee4-226fb0332a14.png)

Google play store button is also missing, we have that in current home page 
https://play.google.com/store/apps/details?id=com.browtricksteauty&utm_campaign=home&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1
![image](https://user-images.githubusercontent.com/14948326/99625853-aeef9d80-2a63-11eb-99ba-f5fb0ba70ce3.png)
