### ISSUE TITLE
[BUG] text input fields require multiple taps to focus

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#533]
# Location

https://deploy-preview-531--browtricks.netlify.app/tenant/pma-media-217/upload

# Expected Behavior

single tap in description field should open keyboard drawer

# Actual Behavior

Multiple taps are required

# Browser, Device, OS and Versions

ios 14.4 - safari

# Steps to Reproduce

What are the steps to reliably reproduce the bug? e.g.

Create account, add a client, add upload photo to client, tap description field 

# Screenshots/casts

https://cdn.discordapp.com/attachments/707811778180153374/804224257444806666/video0.mp4

**Comment by atharva3010** [comment]
I am not able to reproduce this bug on an iOS device with same OS version. I however see the layout being zoomed in and getting non-responsive when the description field gets in focus.

**Comment by paulchrisluke** [comment]
maybe thats the issue @atharva3010 , we can treat that with this issue

**Comment by atharva3010** [comment]
If we fix the "zoomed in" issue, the app will lose the ability to be zoom in by touch on most mobile browsers, iOS Safari would work fine though with pinch to zoom. @paulchrisluke

**Comment by paulchrisluke** [comment]
I think the only case we really want to zoom is on pictures, will that be effected?

**Comment by atharva3010** [comment]
I'd check once, but yes, it's likely that it would be affected too.

**Comment by atharva3010** [comment]
Fixed the issue regarding the input zoom.

**Comment by paulchrisluke** [comment]
approved thank you!
