### ISSUE TITLE
client list

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#55]
![image](https://user-images.githubusercontent.com/14948326/85648068-247c5b00-b6ca-11ea-8071-9f79bfd6928d.png)

This is the first step in our manage clients flow:
https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179

contacts should be listed alphebetical order starting with first letter of first name. That endpoint is being built by backend team in #192.

@sally brought up some design feedback while working on this issue. We have removed the redundant top right + button, and placed "new client" in the FAB button:

![image](https://user-images.githubusercontent.com/5694308/82961729-6ee5bb80-9fe8-11ea-8166-53376cd0a26a.png)

**Comment by sally** [comment]
I am waiting for back-end support on returning clients with separated first name and last name (with the returned list sorted by last name)

**Comment by sally** [comment]
@paulchrisluke could you check-in on the work for returning separated first and last names for clients (with return list sorted by last name)? I am still getting 'name' as the only field when I check on the `ClientModel` in swagger:

![image](https://user-images.githubusercontent.com/20192983/84003036-429e3900-a91e-11ea-88f3-89505a4905a8.png)

**Comment by paulchrisluke** [comment]
@sally I think this is done by @ctyar here https://github.com/whynotearth/meredith-core/issues/192#issuecomment-640451689

**Comment by sally** [comment]
@paulchrisluke Hey, thanks for the reply. I see that the endpoint has been updated but the model still shows only 'name' and no separated out 'first name' and 'last name'.

Here's a screenshot from Swagger currently:

![image](https://user-images.githubusercontent.com/20192983/84061228-62f7e300-a972-11ea-8f21-4ffb9a37671f.png)

**Comment by bamboochow** [comment]
# New Empty State 
![image](https://user-images.githubusercontent.com/14948326/88020390-d6863600-cb55-11ea-8ac6-823120b41a05.png)

Instead of having an empty states screen, we are just showing an empty screen with no contacts for our client list, and allowing them to add new from bottom navigation

**Comment by abdullahcalisir12** [comment]
> # New Empty State
> ![image](https://user-images.githubusercontent.com/14948326/88020390-d6863600-cb55-11ea-8ac6-823120b41a05.png)
> 
> Instead of having an empty states screen, we are just showing an empty screen with no contacts for our client list, and allowing them to add new from bottom navigation

done at #132
