### ISSUE TITLE
Component - Image / File Upload

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#59]
# Similar PR / Code 
**Volkswagen**
Image Upload Component Folder: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/tree/staging/src/components/ImageUpload
EXAMPLE of image upload implementation: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/components/ArticleAddStep2.vue

# Image/File Upload 
![image](https://user-images.githubusercontent.com/14948326/83107207-0a118a80-a0e8-11ea-94fd-bc50881930d5.png)

The image upload section allows users to tap the upload (+) button and use their phone's upload process to add a photo into the article. It is identical in styling to the VW image upload component (see code link above) 

# Text Style
Title: 
```
/* Mobile Body */

font-family: Roboto;
font-style: normal;
font-weight: normal;
font-size: 14px;
line-height: 20px;
/* identical to box height, or 143% */
```

# Color
Title: On Background, High (#000000, 84%) 
Upload Button: On Background, Medium (#000000, 54%) 
Dividers: On Background, Divider (#000000, 12%)

# Usage and Behavior
We will be using this upload module to upload multiple images and files (PDF documents). 
To Upload: 
1. Press + Button 
2. Image Upload Popup from Cloudinary 
3. Image/File is uploaded, preview of file or image shows right of upload image 

# Design File 
https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179
This is the design file for Brow Tricks. The "Tenant CMS" page contains all the screens necessary for the app

**Comment by mort3za** [comment]
@bamboochow 
1. On which page we need an uploader?
2. Do we have an API to keep the uploaded files urls?
3. What should I show for PDF preview (instead of image preview for image files)?

**Comment by bamboochow** [comment]
@mort3za 

1. We will need both an image and a file upload for adding/editing client profile and image upload for adding/editing services (images below) 
2. No, we can use cloudinary for now 
3. Show JPEG of 1st page of PDF 
![image](https://user-images.githubusercontent.com/14948326/83936032-8fccbe80-a7e9-11ea-9fe8-ba7e0951a427.png)
![image](https://user-images.githubusercontent.com/14948326/83936075-ef2ace80-a7e9-11ea-867f-ef2ac3d542b0.png)

**Comment by paulchrisluke** [comment]
@mort3za @ctyar @abdullahcalisir12 this can support video correct? Multiple files?

**Comment by mort3za** [comment]
@paulchrisluke we can add video, needs some changes

**Comment by paulchrisluke** [comment]
videos please <3 @mort3za

**Comment by bamboochow** [comment]
# Video Upload 
Only supports MP4 format, needs to support AVI, MOV, etc (all other video formats) 

Also, after upload, selecting the video opens new window with video player, but should open like images do

Does not support deleting uploaded video either 

# Image Upload 
![unknown (3)](https://user-images.githubusercontent.com/14948326/89410118-59f67880-d74d-11ea-80b1-2d27e9f621d6.png)
Image added, but status not updated 

The grid should have 3 squares per row on mobile 
![image0 (2)](https://user-images.githubusercontent.com/14948326/89410468-f9b40680-d74d-11ea-8288-292ab2f8369a.png)
