### ISSUE TITLE
Component - Top Navigation

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#63]
# Similar Code / PR 
**Volkswagen** 
Top Navigation: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/components/BaseAppBarHeader.vue

**Foodouken**
Top Navigation: 
https://github.com/whynotearth/foodouken.com/blob/staging/src/components/BaseAppBarHeader.vue

# Top Navigation
![image](https://user-images.githubusercontent.com/14948326/83111485-dc7c0f80-a0ee-11ea-888d-2d97eccb8942.png)
This is the top navigation used for most pages in BrowTricks. It is identical in form with Volkswagen and Foodouken's top navigation

# Content 
Title: {{ Page Title }} 
Back: (Leads to {{ Page }} )

# Asset 
![back](https://user-images.githubusercontent.com/5694308/79830196-24609600-83cf-11ea-9f03-e26718f12e6f.png)

# Text Style
Title: 
```
/* Mobile H2 */

font-family: Caviar Dreams;
font-size: 20px;
line-height: 23px;
letter-spacing: 0.15em;
```

# Colors 
Top Nav Bar Background: Primary (#7ACCEA)
Title: On Primary, High Emphasis (#0C6986, 100%)

# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179)
You can find it in the BrowTricks Tenant CMS page

**Comment by sally** [comment]
Addressed in #48
