### ISSUE TITLE
Sign Up - Business Hours 

### ISSUE THREAD

**Issue by paigefreeman271** [whynotearth/BrowTricks#70]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=2887%3A1)

For the design and the flow, go to the Tenant CMS page

# Business Hours 
This is the step in the sign up process where tenants input their business hours 
![image](https://user-images.githubusercontent.com/63047208/84108492-855d2f80-aa4a-11ea-9788-b008de434b91.png)

When they select a day, a pop-up is opened that displays the business hour editor. This page is identical in styling and content to #175 Edit Business Hour, except for the following: 
- an x that closes the pop-up and returns to the previous display
- top navigation replaced with stepper navigation 

If tenant is closed on a certain day, they would set the toggle off, and time selection will not be shown. 

<h1 id="stepper-navigation">1. Stepper Navigation</h1> 

![image](https://user-images.githubusercontent.com/14948326/85554175-dbd38c00-b64e-11ea-9ffb-bb52bc740ad6.png)
![image](https://user-images.githubusercontent.com/63047208/84108620-cfdeac00-aa4a-11ea-8d23-77506a2b11b8.png)

## Content
you can use the same component as below for stepper: 

Stepper: 4 of 6
Title: Business Hours
Subtile: Next: Approvals
Button 1: Back { goes to Sign Up - Notifications #67 )
Button 2: Next Step { goes to Sign Up - Payment Method #71  }

<h1 id="selection">2. Selection</h1> 

![image](https://user-images.githubusercontent.com/63047208/83231275-74443100-a1b5-11ea-9d56-0fa50736064b.png)

## Content 

Selection 1: Monday {{Business hours}}
Selection 2: Tuesday {{Business hours}}
Selection 3: Wednesday {{Business hours}}
Selection 4: Thursday {{Business hours}}
Selection 5: Friday {{Business hours}}
Selection 6: Saturday {{Business hours}}
Selection 7: Sunday {{Business hours}}

## Text Style
Text Selection/Preview:
```
/* Mobile Body */

font-family: Roboto;
font-style: normal;
font-weight: normal;
font-size: 14px;
line-height: 20px;
/* or 143% */

display: flex;
align-items: center;
```

## Color 
Text Selection: On Secondary High Emphasis (#000000, 84%) 
Text Preview: On Background Medium Emphasis (#00000, 54%)

**Comment by bamboochow** [comment]
https://github.com/whynotearth/BrowTricks/pull/118

# Time Toggle Display

Our time toggles are distorted on https://deploy-preview-118--browtricks.netlify.app/auth/sign-up/business-hours. This is identical to foodouken's time picker. 
![image](https://user-images.githubusercontent.com/14948326/87284014-1cbd1300-c520-11ea-9c00-0bd4b25b4561.png)

This is what it looks like on @abdullahcalisir12 's local machine, and this is the correct way this component is supposed to look, but that is not showing up on our deploy previews or staging
[Uploading unknown (9).png…]()

https://staging.foodouken.com/auth/sign-up/business-hours
This is what foodouken's time picker looks like for reference
![unknown (10)](https://user-images.githubusercontent.com/14948326/87284367-7cb3b980-c520-11ea-90a3-2442525b7826.png)

**Comment by bamboochow** [comment]
# Open/Closed Toggle non-functional 
https://gyazo.com/a65bce0830a11ca7554ae11f67e61305

# Weird Shadow
Shadow on mobile view ends at the button, but should leave a little space at bottom 
![Screenshot_20200713-171919](https://user-images.githubusercontent.com/14948326/87293938-3749b900-c52d-11ea-9141-e5751c5d0e9d.png)

**Comment by paulchrisluke** [comment]
solved in https://github.com/whynotearth/BrowTricks/pull/120#pullrequestreview-447169054
