### ISSUE TITLE
Tenant Site - View / Edit Client Profile

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#72]
# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179)

**You can find the designs for this issue in the "Tenant CMS" Page of Figma**

# Affected Code 
**BrowTricks**
Top Navigation: https://github.com/whynotearth/BrowTricks/blob/master/src/components/BaseHeader.vue
Button: https://github.com/whynotearth/BrowTricks/blob/master/src/components/BaseButton.vue

# View / Edit Client Profile
This page is almost identical to the "Add client" page with these exceptions 
- [ ] Profile Header 
- [ ] Prefilled Information
- [ ] Editing Feature 
- [ ] Archive Client feature 

![image](https://user-images.githubusercontent.com/14948326/84375908-6e653b80-ac0a-11ea-84c3-5a4f3f71878c.png)

# Profile Header 

![image](https://user-images.githubusercontent.com/14948326/84375842-54c3f400-ac0a-11ea-852b-1863a9590d45.png)
### Content 
Avatar: { Social Media Profile Picture. If not, then 1st image uploaded. If not, then empty state placeholder }
Title: {First Name } {Last Name} 
Button 1: Book (Opens "new Appointment" form) 
Button 2: Email (opens phone's email feature)
Button 3: Text (Opens phone's text feature with saved phone number)
Button 4: Call (Phone calls saved phone number) 

### Color 
Header background: Action / Icon / Accent Color 
All content: On background image - High 

### Text Style 
Title: Mobile H1
Buttons: Caption

# Prefilled Information 
This page displays previously saved client information, as well as display previews from previously uploaded pictures and PMU files 

# Editing Feature 
When tenant taps any of the text fields to change information, a save button will appear at the bottom. To save their changes they must tap the button. 

# Delete Client Feature 
There is a "Delete Client" text button at the bottom of the page 
Pressing this deletes this client's profile and returns to clients list #55

**Comment by bamboochow** [comment]
@sally 
# Delete Client Feature Dialog
![image](https://user-images.githubusercontent.com/14948326/84374756-a8354280-ac08-11ea-8f2b-8f8009bdac61.png)

On taping "archive client", show dialog pop-up in above screenshot 

## Content 
Text: Archive client? 
Button 1: Cancel
Button 2: Archive 

## Color 
Card: Surface
Text: On Background, Medium
Button 1: Error
Button 2: Secondary 

## Text Style 
Text: Mobile Body 
Buttons: Mobile Color Label 

## Shadow 
Card Background: 
```
/* 24 dp */

background: #C4C4C4;
box-shadow: 0px 11px 15px rgba(0, 0, 0, 0.2), 0px 9px 46px rgba(0, 0, 0, 0.12), 0px 24px 38px rgba(0, 0, 0, 0.14);
```

**Comment by bamboochow** [comment]
# Editing Info 
Saved editing info is shown within the page https://browtricks.netlify.app/tenant/julia-89/clients/edit/42 , but once you return to the client page https://browtricks.netlify.app/tenant/julia-89/clients the changes you've made to name are not persisted 
This is true for: 
- First Name 
- Last Name 
- Phone number 

When changing email, if email is edited to existing email (same as another client), then all information will change to match previously added client instead of the new information you added. 

![gif](https://i.gyazo.com/59b15fb3f783c5088c7ad0e88d266b3a.gif)
![image](https://user-images.githubusercontent.com/14948326/88358576-ae871480-cd99-11ea-8f8e-5777499bbc07.png)

# Archiving Client 
Archiving a client does not actually archive a client, but shows success screen

**Comment by abdullahcalisir12** [comment]
@bamboochow updating client info and archiving client problems are both backend issues @ctyar 

https://github.com/whynotearth/meredith-core/issues/267

https://github.com/whynotearth/BrowTricks/issues/129

**Comment by ctyar** [comment]
@bamboochow Both archiving and edit should be fixed now

**Comment by paulchrisluke** [comment]
confirmed @ctyar
