### ISSUE TITLE
Tenant CMS - Notes Page

### ISSUE THREAD

**Issue by paigefreeman271** [whynotearth/BrowTricks#73]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179)
You can find it in the BrowTricks Tenant CMS page under settings

# Business Hours
Your mission, should you accept, includes these tasks: 

- [ ] 1. [Top Navigation ](#top-navigation) 
- [ ] 2. [Button](#button) 
- [ ] 3. [Notes](#notes)

![image](https://user-images.githubusercontent.com/14948326/85825243-eeafa300-b7ab-11ea-8954-2c865f21cb67.png)

<h1 id="top-navigation">1. Top Navigation</h1> 

USE THIS CODE:
https://github.com/whynotearth/BrowTricks/blob/master/src/components/BaseHeader.vue

![image](https://user-images.githubusercontent.com/14948326/85825255-f5d6b100-b7ab-11ea-9c93-2f27334d96d7.png)

## Content 
Title: Notes
Back: (Leads to page before)

## Color 
Top Nav Background: Primary (#067BC2)
Top Nav Title, Icon: On Primary (#FFFFFF, 84%) 

<h1 id="buttons">2. Buttons</h1> 

USE THIS CODE: BUTTON: https://github.com/whynotearth/BrowTricks/blob/master/src/components/BaseButton.vue

![image](https://user-images.githubusercontent.com/14948326/85825541-b066b380-b7ac-11ea-9540-bd8ec3c917f2.png)

## Content 
Button Text: Tap For New Note {{clicking this button will create a new note below}}

## Text Style
Button Text:
```
/* Color Label */

font-family: Roboto;
font-style: normal;
font-weight: 500;
font-size: 14px;
line-height: 24px;
/* or 171% */

text-align: center;
letter-spacing: 0.02em;
text-transform: uppercase;
```

## Color 
Button Text: On Secondary, High (#FFFFFF, 84%)
Button: Secondary (#33658A, 100%)

<h1 id="notes">3. Notes</h1> 

![image](https://user-images.githubusercontent.com/14948326/85825505-94631200-b7ac-11ea-899c-c8db396d98c1.png)

## Content
Each card is a note that has been added for this client or appointment 

## Text Style
```
/* Mobile H3 */

font-family: Roboto;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 24px;
/* identical to box height, or 150% */

display: flex;
align-items: center;
```
## Color
Text: On Surface, High Emphasis (#FFFFFF, 84%)
Text Card : Surface (#FFFFFF, 100%)

**Comment by bamboochow** [comment]
# Autogenerated Dates for Notes 
We are adding autogenerated dates to each note added 

**Style** 
Date color: on surface, medium (#FFFFFF, 54%) 
Date text: 
```
/* Mobile Caption */

font-family: Roboto;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
/* identical to box height, or 133% */
```

![image](https://user-images.githubusercontent.com/14948326/88021001-e6524a00-cb56-11ea-80c7-63e93454d5a7.png)
