### ISSUE TITLE
Tenant Sign Up - Welcome

### ISSUE THREAD

**Issue by paigefreeman271** [whynotearth/BrowTricks#76]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179)
You can find it in the BrowTricks Tenant CMS page 

# Business Hours
Your mission, should you accept, includes these tasks: 

This is the starting page for brow tricks's tenant signup 
START WITH THIS CODE : https://github.com/whynotearth/BrowTricks/blob/master/src/components/LayoutSplash.vue

- [ ] 1. [Title](#title) 
- [ ] 2. [Button](#button) 
- [ ] 3. [Hyperlink](#hyperlink)

![image](https://user-images.githubusercontent.com/14948326/85540475-38c84580-b641-11ea-9d45-03ce011bb486.png)

<h1 id="title">1. Title</h1> 

![image](https://user-images.githubusercontent.com/63047208/83621279-a9d38a80-a5b8-11ea-81f1-a1f84412a393.png)

## Content 
Title: Brow Tricks Beauty

## Text Style
```
/* Mobile H2 */

font-family: Caviar Dreams;
font-style: normal;
font-weight: bold;
font-size: 20px;
line-height: 25px;
text-align: center;
letter-spacing: 0.15em;
```

##Color
Title: On background, high emphasis (#FFFFFF, 100%)

<h1 id="button">2. Button</h1> 

![image](https://user-images.githubusercontent.com/14948326/85540541-51386000-b641-11ea-85c1-fce290c527fc.png)

## Content 
Button Text: START SETTING UP YOUR BUSINESS {{button leads to business info #65 )

##Text Style
```
/* Color Label */

font-family: Roboto;
font-style: normal;
font-weight: 500;
font-size: 14px;
line-height: 24px;
/* identical to box height, or 171% */

display: flex;
align-items: center;
text-align: center;
letter-spacing: 0.02em;
text-transform: uppercase;
```

## Color
Button Title: On secondary, high emphasis (0C6986, 100%)
Button: Secondary (#33658A, 100%)

<h1 id="hyperlink">3. Hyperlink</h1> 

![image](https://user-images.githubusercontent.com/63047208/83624170-7c88db80-a5bc-11ea-8c72-7f1374391ed8.png)

## Content
Hyperlink Text: Already have an account? Log in! (Goes to "log in" page )

## Text Style
```
/* Mobile Body 1 (Hyperlink) */

font-family: Roboto;
font-style: normal;
font-weight: normal;
font-size: 14px;
line-height: 20px;
/* identical to box height, or 143% */

display: flex;
align-items: center;
text-align: center;
text-decoration-line: underline;
```
## Color
Hyperlink Text: On background image, medium emphasis (#FFFFFF, 54%)

**Comment by sally** [comment]
@bamboochow We were chatting earlier last week about a more standardized view for views of this type:

![image](https://user-images.githubusercontent.com/20192983/84002870-f81cbc80-a91d-11ea-9034-0444efc48e1a.png)

Is the work for that done now in Figma? Thanks

**Comment by bamboochow** [comment]
@sally I have the base template for all of these pages, but i don't have these individual pages out yet. If this is enough to get you started, i can write an issues for these base splash screen page (this page is from Master Component file https://www.figma.com/file/uUfdtGdDMwvZsC5xsM5Lwg/Master-Components?node-id=7%3A27) 

![image](https://user-images.githubusercontent.com/14948326/84004433-bf202e80-a995-11ea-9715-cfa2199e64a6.png)

**Comment by sally** [comment]
@bamboochow Okay, thanks. It looks like the 'Welcome Page' has that low opacity small text link but the master component for that type of view doesn't. Would that go under the 'Cancel Order' sample red text?

**Comment by paulchrisluke** [comment]
@sally yes, we will update

**Comment by sally** [comment]
Some notes after chatting with Chris and Julia:

- Buttons are being updated across the app to have a rounder border-radius:

![image](https://user-images.githubusercontent.com/20192983/84225061-10621800-aa93-11ea-88c6-c30971d6d998.png)

- The 'splash page' layout view will have bottom-aligned content, where the content will 'grow' upwards from the page (with some bottom padding)
