### ISSUE TITLE
My Account (Brow Tricks)

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#83]
# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179)

See page "Tenant CMS (Prototype) 

# My Account

This is a "My Accounts" page where users can access their personal information, payment and subscription activity, as well as switch to a business account to manage their business. The "more" Icon opens settings page 

![image](https://user-images.githubusercontent.com/14948326/91563012-5c24af00-e968-11ea-930e-0f4ed1fc67a6.png)

**Comment by paulchrisluke** [comment]
@giteshk11 this issue image is slightly out of date. we should use the active/inactive stuff you built for foodouken subscibtion services

**Comment by paulchrisluke** [comment]
@giteshk11 this is "my account" similar to the changes you just made for the client profile. Difference is that in the 3 dot area you get business management tabs, activity, payment methods... but those are still being worked on by backend. For now, you can move the changes you made to client profile here to the my account view

**Comment by bamboochow** [comment]
![image](https://user-images.githubusercontent.com/14948326/91562831-0a7c2480-e968-11ea-98c6-b82f4e4d35f5.png)
Updated "My Account" Design will not have the mini menu, instead that icon will open the Settings page 

the top navigation will now include a drawer that allows you to switch to a different account (e.g. switch from private user account to public business account and manage business info)

**Comment by giteshk11** [comment]
![https://cdn.discordapp.com/attachments/707811778180153374/749215159171416185/unknown.png](https://cdn.discordapp.com/attachments/707811778180153374/749215159171416185/unknown.png)
Need the data mentioned above in the pic

**Comment by paulchrisluke** [comment]
@giteshk11 for now, if we do not have this info via api, can you show it in disabled state?

**Comment by giteshk11** [comment]
we can @paulchrisluke

**Comment by paulchrisluke** [comment]
lets do that and merge this one if its ready then, big feature we should link to bottom nav and such

**Comment by paulchrisluke** [comment]
this issue is looking good for now. Putting on backlog while we finish the API needed for the rest of these screens
