### ISSUE TITLE
Account Payment Activity

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/BrowTricks#84]
# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=3388%3A1997)

**You can find the designs for this issue in the "Tenant CMS" Page of Figma** 

# Account Payment Activity
this page displays all payment associated with selected account. 
this page is access from Settings --> Billing --> Activity 

- [ ] 1. [Top Navigation](#stepper-navigation)
- [ ] 2. [Billing Listing](#billing-listing)

![image](https://user-images.githubusercontent.com/14948326/91562383-52e71280-e967-11ea-82e7-0cc7bc8dd1a7.png)

<h1 id="top-navigation">1. Top Navigation</h1> 

USE THIS CODE: https://github.com/whynotearth/BrowTricks/blob/master/src/components/BaseHeader.vue

![image](https://user-images.githubusercontent.com/63047208/85196723-5e361600-b306-11ea-84db-664f4b97eabd.png)

## Content 
Title: Activity
Back: (Leads to My Account)

## Asset 
![back](https://user-images.githubusercontent.com/5694308/79830196-24609600-83cf-11ea-9f03-e26718f12e6f.png)

## Text Style
Title: 
```
/* Mobile H2 */

font-family: Caviar Dreams;
font-size: 20px;
line-height: 23px;
letter-spacing: 0.15em;
```

## Colors 
Top Nav Bar Background: Primary (#067BC2)
Title: On Primary, High Emphasis (#FFFFFF, 84%)

## Shadow 
Top Navigation Bar; 
```
/* 4 dp */

background: #C4C4C4;
box-shadow: 0px 1px 10px rgba(0, 0, 0, 0.2), 0px 4px 5px rgba(0, 0, 0, 0.12), 0px 2px 4px rgba(0, 0, 0, 0.14);
```

<h1 id="Billing List">2. Billing List</h1> 

This is a list of all payment activity associated with this tenant's account 

![image](https://user-images.githubusercontent.com/63047208/85197710-f59e6780-b30c-11ea-8a59-28b94dd001f3.png)

## Content

PLEASE SEE THIS ISSUE FOR THIS COMPONENT:

https://github.com/whynotearth/BrowTricks/issues/91

**Comment by paulchrisluke** [comment]
duplicate #252
